The Most Popular Client_Id Among Users Using Video and Voice Calls

Select the most popular client_id based on a count of the number of users who have at least 50% of their events from the following list: 'video call received', 'video call sent', 'voice call received', 'voice call sent'.

In [1]:
import pandas as pd

In [3]:
fact_events = pd.read_excel("../CSV/fact_events.xlsx", header=1)
fact_events.head()

,id,time_id,user_id,customer_id,client_id,event_type,event_id
0,1,2020-02-28,3668-QPYBK,Sendit,desktop,message sent,3
1,2,2020-02-28,7892-POOKP,Connectix,mobile,file received,2
2,3,2020-04-03,9763-GRSKD,Zoomit,desktop,video call received,7
3,4,2020-04-02,9763-GRSKD,Connectix,desktop,video call received,7
4,5,2020-02-06,9237-HQITU,Sendit,desktop,video call received,7

In [4]:
events_list = ['video call received', 'video call sent', 'voice call received', 'voice call sent']

In [5]:
fact_events['event_check'] = fact_events['event_type'].apply(lambda x: 1 if x in events_list else 0)
fact_events.head(10)

,id,time_id,user_id,customer_id,client_id,event_type,event_id,event_check
0,1,2020-02-28,3668-QPYBK,Sendit,desktop,message sent,3,0
1,2,2020-02-28,7892-POOKP,Connectix,mobile,file received,2,0
2,3,2020-04-03,9763-GRSKD,Zoomit,desktop,video call received,7,1
3,4,2020-04-02,9763-GRSKD,Connectix,desktop,video call received,7,1
4,5,2020-02-06,9237-HQITU,Sendit,desktop,video call received,7,1
5,6,2020-02-27,8191-XWSZG,Connectix,desktop,file received,2,0
6,7,2020-04-03,9237-HQITU,Connectix,desktop,video call received,7,1
7,8,2020-03-01,9237-HQITU,Connectix,mobile,message received,4,0
8,9,2020-04-02,4190-MFLUW,Connectix,mobile,video call received,7,1
9,10,2020-04-21,9763-GRSKD,Sendit,desktop,file received,2,0

In [12]:
fact_events['event_check_mean'] = fact_events.groupby('user_id')['event_check'].transform('mean')
fact_events.head(10)

,id,time_id,user_id,customer_id,client_id,event_type,event_id,event_check,event_check_mean
0,1,2020-02-28,3668-QPYBK,Sendit,desktop,message sent,3,0,0.090909
1,2,2020-02-28,7892-POOKP,Connectix,mobile,file received,2,0,0.000000
2,3,2020-04-03,9763-GRSKD,Zoomit,desktop,video call received,7,1,0.400000
3,4,2020-04-02,9763-GRSKD,Connectix,desktop,video call received,7,1,0.400000
4,5,2020-02-06,9237-HQITU,Sendit,desktop,video call received,7,1,0.600000
5,6,2020-02-27,8191-XWSZG,Connectix,desktop,file received,2,0,0.125000
6,7,2020-04-03,9237-HQITU,Connectix,desktop,video call received,7,1,0.600000
7,8,2020-03-01,9237-HQITU,Connectix,mobile,message received,4,0,0.600000
8,9,2020-04-02,4190-MFLUW,Connectix,mobile,video call received,7,1,0.142857
9,10,2020-04-21,9763-GRSKD,Sendit,desktop,file received,2,0,0.400000

In [11]:
res = fact_events[fact_events.user_id == '4190-MFLUW']
res

,id,time_id,user_id,customer_id,client_id,event_type,event_id,event_check,event_check_mean
8,9,2020-04-02,4190-MFLUW,Connectix,mobile,video call received,7,1,7
39,40,2020-03-25,4190-MFLUW,Connectix,mobile,file received,2,0,7
46,47,2020-04-06,4190-MFLUW,Connectix,mobile,file sent,1,0,7
62,63,2020-03-07,4190-MFLUW,Electric Gravity,desktop,message sent,3,0,7
63,64,2020-03-05,4190-MFLUW,Connectix,desktop,file sent,1,0,7
74,75,2020-03-02,4190-MFLUW,Sendit,mobile,message sent,3,0,7
125,126,2020-03-25,4190-MFLUW,Connectix,desktop,video call started,6,0,7

In [14]:
res_05_and_more = fact_events[fact_events.event_check_mean >= 0.5]
res_05_and_more

,id,time_id,user_id,customer_id,client_id,event_type,event_id,event_check,event_check_mean
4,5,2020-02-06,9237-HQITU,Sendit,desktop,video call received,7,1,0.6
6,7,2020-04-03,9237-HQITU,Connectix,desktop,video call received,7,1,0.6
7,8,2020-03-01,9237-HQITU,Connectix,mobile,message received,4,0,0.6
14,15,2020-02-11,9237-HQITU,Connectix,desktop,video call received,7,1,0.6
31,32,2020-02-15,9237-HQITU,Connectix,mobile,message sent,3,0,0.6
32,33,2020-04-06,4183-MYFRB,Sendit,desktop,file received,2,0,0.5
36,37,2020-04-03,4183-MYFRB,Connectix,desktop,message received,4,0,0.5
57,58,2020-02-27,9237-HQITU,eShop,desktop,video call received,7,1,0.6
71,72,2020-03-09,9237-HQITU,Sendit,desktop,video call received,7,1,0.6
84,85,2020-02-17,9237-HQITU,Connectix,desktop,file sent,1,0,0.6
101,102,2020-03-02,9237-HQITU,Connectix,desktop,voice call received,9,1,0.6
108,109,2020-02-03,9237-HQITU,Sendit,mobile,video call started,6,0,0.6
112,113,2020-03-25,4183-MYFRB,Sendit,desktop,video call received,7,1,0.5
130,131,2020-03-27,4183-MYFRB,Connectix,desktop,voice call received,9,1,0.5

In [13]:
result = fact_events[fact_events['event_check_mean']>=0.5].groupby('client_id')['id'].count().reset_index()
result

  client_id  id
0   desktop  11
1    mobile   3

In [15]:
result['ranking'] = result['id'].rank(ascending=False)
result

  client_id  id  ranking
0   desktop  11      1.0
1    mobile   3      2.0

In [16]:
result = result[result.ranking == 1][['client_id']]
result

  client_id
0   desktop

Solution Walkthrough
This walkthrough will explain the code snippet and provide a step-by-step guide on how it solves the problem of selecting the most popular client_id based on the count of users who have at least 50% of their events from a specific list.

Understanding The Data
The code snippet utilizes a data structure called a dataframe, which is a popular data manipulation tool in data analysis and data science. In this case, the dataframe is created using the pandas library, which is imported at the beginning of the code with the alias 'pd'.

The dataframe has several columns, including 'user_id', 'event_type', and 'client_id'. Each row represents an event recorded in the dataset.

The Problem Statement
The goal of the code snippet is to select the most popular client_id based on the count of users who have at least 50% of their events from a specific list. The specific list is defined by the events_list variable, which contains the event types "video call received", "video call sent", "voice call received", and "voice call sent".

The code accomplishes this by performing a series of transformations and calculations on the dataframe.

Breaking Down The Code
Let's break down the code snippet into smaller parts to understand its functionality.

import pandas as pd
This line imports the pandas library and assigns it the alias 'pd'. The pandas library is used to create and manipulate the dataframe.

events_list = [
    "video call received",
    "video call sent",
    "voice call received",
    "voice call sent",
]
This line creates a list called 'events_list' that contains the event types the code snippet is interested in.

fact_events["event_check"] = fact_events["event_type"].apply(
    lambda x: 1 if x in events_list else 0
)
This line creates a new column in the dataframe called 'event_check'. The 'event_check' column contains a 1 if the corresponding 'event_type' value is in the 'events_list', and 0 otherwise. This effectively checks if an event belongs to the specific list.

fact_events["event_check_mean"] = fact_events.groupby("user_id")[
    "event_check"
].transform("mean")
This line creates another new column in the dataframe called 'event_check_mean'. It calculates the mean of the 'event_check' column for each unique 'user_id' in the dataframe and assigns that mean value to every row with the same 'user_id'.

result = (
    fact_events[fact_events["event_check_mean"] >= 0.5]
    .groupby("client_id")["id"]
    .count()
    .reset_index()
)
This line filters the dataframe to only include rows where the 'event_check_mean' value is greater than or equal to 0.5. Then, it groups the filtered dataframe by the 'client_id' column, counts the number of 'id' values (assuming 'id' is the column that uniquely identifies each event), and resets the index.

result["ranking"] = result["id"].rank(ascending=False)
This line adds a new column called 'ranking' to the 'result' dataframe. It assigns a rank to each 'id' value based on its count, with a higher count receiving a lower rank.

result = result[result.ranking == 1][["client_id"]]
This line filters the 'result' dataframe to only include rows where the 'ranking' value is equal to 1. It selects the 'client_id' column from the filtered dataframe.

Bringing It All Together
The code snippet first creates a list that defines the specific event types of interest. It then adds a new column to the dataframe that checks if an event belongs to the specific list. Next, it calculates the mean of the 'event_check' column for each unique 'user_id'.

Then, it filters the dataframe based on the calculated mean value, groups the filtered dataframe by 'client_id', counts the number of 'id' values, assigns ranks to each count, and filters the result to only include the rows with a rank of 1. Finally, it selects the 'client_id' column from the filtered result.

Conclusion
The code snippet successfully selects the most popular 'client_id' based on the count of users who have at least 50% of their events from the specific list defined by the 'events_list' variable.